### ISSUE TITLE
error on running notebook 

### ISSUE THREAD

**Issue by iut62elec** [aws-samples/amazon-forecast-samples#2]
------------------
I get this error after running python code at 'forecast.create_dataset' function line.

 

IAM role for Amazon Forecast:  arn:aws:iam::83424617XXXX:role/amazonforecast
Traceback (most recent call last):
  File "H:\Run_07_19_2017\AWS_forecast\amazon-forecast-samples-master\run_me2.py", line 200, in <module>
    Schema = schema
  File "C:\Anaconda3\lib\site-packages\botocore\client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Anaconda3\lib\site-packages\botocore\client.py", line 624, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceAlreadyExistsException: An error occurred (ResourceAlreadyExistsException) when calling the CreateDataset operation: Failed to create Dataset

----------------------
I attach my python file here (changed extension to '.png' to attach' 
![run_me2](https://user-images.githubusercontent.com/7864200/50265333-0966c600-0417-11e9-9a78-0646adf661b7.png)

**Comment by akhilrazdan** [comment]
This is because the dataset that you created already exists, and you're trying to create it again.

**Comment by iut62elec** [comment]
I changed the datasetName as ‘'workshop_ds1' and datasetGroupName as 'workshop1_gp1'and re-run, I get this error at ‘createPredictorResponse = forecast.create_predictor(XXX)’ line

IAM role for Amazon Forecast:  arn:aws:iam::83424617XXX:role/amazonforecast
36465b3f
. 
. 
. 
. 
. 
. 
. 
. 
. 

FAILED
Traceback (most recent call last):
  File "H:\Run_07_19_2017\AWS_forecast\amazon-forecast-samples-master\run_me2.py", line 292, in <module>
    ForecastHorizon = forecastHorizon)
  File "C:\Anaconda3\lib\site-packages\botocore\client.py", line 320, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "C:\Anaconda3\lib\site-packages\botocore\client.py", line 624, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.errorfactory.ResourceNotFoundException: An error occurred (ResourceNotFoundException) when calling the CreatePredictor operation: No active imported dataset item for dataset: 'workshop1_ds1'
