### ISSUE TITLE
AccessDeniedException when calling the CreateDataset operation

### ISSUE THREAD

**Issue by PoojaSharma10** [aws-samples/amazon-forecast-samples#21]
I have setup AWS CLI, configured my aws account and added aws service models forecast and forecastquery. I am getting below exception while running - 
Traceback (most recent call last):
  File "bike_example/create_dataset_and_forecast.py", line 208, in <module>
    execute()
  File "bike_example/create_dataset_and_forecast.py", line 59, in execute
    Schema=schema
  File "/home/poojsh/workspace/testpythonmodule/env/TestPoojshPythonModule-1.0/runtime/lib/python3.6/site-packages/botocore/client.py", line 357, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/home/poojsh/workspace/testpythonmodule/env/TestPoojshPythonModule-1.0/runtime/lib/python3.6/site-packages/botocore/client.py", line 661, in _make_api_call
    raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (AccessDeniedException) when calling the CreateDataset operation:

**Comment by akhilrazdan** [comment]
Hello, 

Thanks for your interest. We currently only accept new whitelists through https://aws.amazon.com/forecast/ 
Whitelisting is temporarily closed, and will open shortly. Meanwhile, please submit the request using the link above.
